services:
  backend:
    build: .
    container_name: fastapi_app
    extra_hosts:
      - "host.docker.internal:host-gateway"
#    expose:
#      - "8080"
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true