services:
  backend:
    build: .
    container_name: fastapi_app
#    expose:
#      - "8080"
    ports:
      - "8011:8011"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true