"""Customer2

Revision ID: 6de2ab37cb25
Revises: b38bdde6c53a
Create Date: 2025-09-14 16:57:30.589422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de2ab37cb25'
down_revision: Union[str, None] = 'b38bdde6c53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone', sa.String(length=20), nullable=False))
    op.drop_column('customers', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('customers', 'phone')
    # ### end Alembic commands ###
