"""Customer1

Revision ID: b38bdde6c53a
Revises: 6da9c813b59b
Create Date: 2025-09-14 16:54:10.294731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38bdde6c53a'
down_revision: Union[str, None] = '6da9c813b59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('customers', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('customers', 'password')
    # ### end Alembic commands ###
