name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "${{ secrets.SSH_TARGET_DIR }}"
          rm: true
          strip_components: 0
          overwrite: true

      - name: Build and restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cp "/root/.env" "${{ secrets.SSH_TARGET_DIR }}/.env"
            cd "${{ secrets.SSH_TARGET_DIR }}"
            docker compose up --build -d
